language: php

php:
  - '7.0'
  - '7.1'

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-clover clover.xml
  - php coverage-checker.php clover.xml 100
  - vendor/bin/humbug
  - php mutation-checker.php humbug-log.json 65 # Someday it will be 100

before_script:
  - composer install
