language: php

php:
  - '7.0'
  - '7.1'

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-clover clover.xml
  - php coverage-checker.php clover.xml 70 #+10% every new release

before_script:
  - composer install